name: build
on:
  push:
  pull_request:
    branches:
      - 'master'

env:
  VCPKG_FEATURE_FLAGS: manifests

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'Windows x64'
            os: windows-latest
            triplet: x64-windows
            vcpkg_dir: 'C:\vcpkg'
            suffix: 'windows-win64'
            generator: 'Visual Studio 16 2019'
            arch: '-A x64'
          - name: 'Windows x86'
            os: windows-latest
            triplet: x86-windows
            vcpkg_dir: 'C:\vcpkg'
            suffix: 'windows-win32'
            generator: 'Visual Studio 16 2019'
            arch: '-A Win32'

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Install vcpkg packages
        shell: bash
        run: |
          cd pulsar-client-cpp && vcpkg install --triplet ${{ matrix.triplet }}

      - name: Configure
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            cd pulsar-client-cpp && \
            cmake \
              -B ./build \
              -G "${{ matrix.generator }}" ${{ matrix.arch }} \
              -DBUILD_PYTHON_WRAPPER=OFF -DBUILD_TESTS=OFF \
              -DVCPKG_TRIPLET=${{ matrix.triplet }} \
              -DCMAKE_BUILD_TYPE=Release \
              -S .
          fi

      - name: Compile
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            cd pulsar-client-cpp && \
            cmake --build ./build --target INSTALL --config MinSizeRel
          fi
